# Generated by Django 4.1.3 on 2022-11-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['roll', 'fname', 'email'],
            },
        ),
    ]
